const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";

CONSTANTS.MONGODB = {};
CONSTANTS.MONGODB.URL = "localhost:27017";
CONSTANTS.MONGODB.DATABASE = "hackcare";

CONSTANTS.SENDGRID = {};
CONSTANTS.SENDGRID.KEY = "~";

CONSTANTS.BCRYPT_SALT_ROUNDS = 10;


module.exports = CONSTANTS;
