const CONSTANTS = {};
CONSTANTS.ENDPOINT = {};

CONSTANTS.PORT = process.env.PORT || "3001";
CONSTANTS.ENDPOINT.GRID = "/grid";

CONSTANTS.ENDPOINT.LIST = "/list";

CONSTANTS.ENDPOINT.MASTERDETAIL = "/masterdetail";

CONSTANTS.MONGODB = {};
CONSTANTS.MONGODB.URL = "localhost:27017";
CONSTANTS.MONGODB.DATABASE = "hackcare";

CONSTANTS.SENDGRID = {};
CONSTANTS.SENDGRID.KEY = "~";

CONSTANTS.BCRYPT_SALT_ROUNDS = 10;


module.exports = CONSTANTS;
